### ISSUE TITLE
Compile libstorj statically to node bindings

### ISSUE THREAD

**Issue by braydonf** [Storj/node-libstorj#14]
Compile libstorj library to the node bindings and include prebuild binaries for distribution so that having libstorj installed on the system is optional.

**Todo:**
- [x] Release libstorj with build including necessary archive files https://github.com/Storj/libstorj/releases/tag/v1.1.0-beta
- [x] Have build script download libstorj releases and build bindings linked to archive files https://github.com/Storj/node-libstorj/pull/32
- [x] Fix paths to be relative in `bindings.gyp` https://github.com/Storj/node-libstorj/pull/30
- [x] Use `libstorj.so` on system if available, by default https://github.com/Storj/node-libstorj/pull/30
