### ISSUE TITLE
Bindings checklist

### ISSUE THREAD

**Issue by mobyvb** [Storj/node-libstorj#15]
These are functions in `libstorj/src/storj.h` to be bound:

- [x] `int storj_mnemonic_generate(int strength, char **buffer)`
- [x] `bool storj_mnemonic_check(const char *mnemonic)`
- [x] `int storj_bridge_get_info(storj_env_t *env, void *handle, uv_after_work_cb cb)`
- [x] `int storj_bridge_get_buckets(storj_env_t *env, void *handle, uv_after_work_cb cb)`
- [x] `int storj_bridge_create_bucket(storj_env_t *env, const char *name, void *handle, uv_after_work_cb cb)`
- [x] `int storj_bridge_delete_bucket(storj_env_t *env, const char *id, void *handle, uv_after_work_cb cb)`
- [x] `int storj_bridge_list_files(storj_env_t *env, const char *id, void *handle, uv_after_work_cb cb)`
- [x] `int storj_bridge_delete_file(storj_env_t *env, const char *bucket_id, const char *file_id, void *handle, uv_after_work_cb cb)`
- [x] `int storj_bridge_store_file_cancel(storj_upload_state_t *state)`
- [x] `int storj_bridge_store_file(storj_env_t *env, storj_upload_state_t *state, storj_upload_opts_t *opts, void *handle, storj_progress_cb progress_cb, storj_finished_upload_cb finished_cb)`
- [x] `int storj_bridge_resolve_file_cancel(storj_download_state_t *state)`
- [x] `int storj_bridge_resolve_file(storj_env_t *env, storj_download_state_t *state, const char *bucket_id, const char *file_id, FILE *destination, void *handle, storj_progress_cb progress_cb, storj_finished_download_cb finished_cb)`

**Comment by braydonf** [comment]
Added resolveFileCancel in https://github.com/Storj/node-libstorj/commit/3027fcb0de7911328b95ec052f10cdce85784f7f
