### ISSUE TITLE
Additional bindings checklist

### ISSUE THREAD

**Issue by braydonf** [storj/node-libstorj#25]
Some extra bindings that might be useful:
- [x] `int storj_bridge_register(storj_env_t *env, const char *email, const char *password, void *handle, uv_after_work_cb cb)`
- [ ] `int storj_bridge_get_bucket(storj_env_t *env, const char *id, void *handle, uv_after_work_cb cb)`
- [x] `uint64_t storj_util_timestamp()`
- [ ] `int storj_bridge_get_file_info(storj_env_t *env, const char *bucket_id, const char *file_id, void *handle, uv_after_work_cb cb)`
- [ ] `int storj_bridge_list_mirrors(storj_env_t *env, const char *bucket_id, const char *file_id, void *handle, uv_after_work_cb cb)`

New in 2.0.0:
- [x] `int storj_bridge_get_bucket_id(storj_env_t *env, const char *name, void *handle, uv_after_work_cb cb)`
- [ ] `int storj_bridge_get_file_id(storj_env_t *env, const char *bucket_id, const char *file_name, void *handle, uv_after_work_cb cb)`

**Comment by Azael05x** [comment]
It would be useful to have authentication by key, which was available for BridgeClient no Storj/core.

**Comment by braydonf** [comment]
@Azael05x this would be a feature for https://github.com/Storj/libstorj rather than a binding, it's something that is likely to be added, and to be able to authenticate by only having the "encryption key" as their can be a private key derived from it for the purpose of signing requests.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
