### ISSUE TITLE
Finish remaining TODO in libstorj.cc

### ISSUE THREAD

**Issue by braydonf** [Storj/node-libstorj#36]
- [ ] Check initialization of state
- [ ] Check status on storj file and resolve file
- [ ] Have overwrite be an option in resolve file
- [ ] Give error in callback if file can't be opened for resolve file
